name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy crosstraining.top 🚀
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6223c798a22dd19c7b80dcce
