name: 'GitHub Actions Weekly Robot'

on:
  schedule:
    - cron: '55 7 * * 4'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: { ref: main }
      - name: Weekly Reporter
        run: curl -X POST -H 'Content-Type:application/json' -d '{"msg_type":"text","content":{"text":"<at user_id = \"all\">All</at> 周报周报～"}}' https://open.feishu.cn/open-apis/bot/v2/hook/b761e15f-c8ac-4e31-8612-1443f487d3a1
