name: 'GitHub Actions Food Robot'

on:
  schedule:
    - cron: '43 9 * * 1-5'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: { ref: main }
      - name: Food Robot
        run: curl -X POST -H 'Content-Type:application/json' -d '{"msg_type":"text","content":{"text":"<at user_id = \"all\">All</at> 点外卖啦～点外卖啦～"}}' https://open.feishu.cn/open-apis/bot/v2/hook/98081b21-bd3f-4ed8-a9a0-f978294e3f18
